### PR TITLE
Resolves #13. Now resolves the longest alias match

### LINKED ISSUE #13: Resolve longest match first
Given:

```
moduleAlias.addAliases({
    "react-dom": "preact-compat-enzyme",
    "react-dom/server": "preact-render-to-string"
});
```

An attempt to `require('react-dom/server')` yields `Error: Cannot find module 'preact-compat-enzyme/server'`.

I believe the simple solution would be to evaluate possible matches, and choose the longest.

### PR DESCRIPTION
**Pull request by thomas-p-wilson**
Given aliases such as:
```
"react-dom": "preact-compat-enzyme",
"react-dom/server": "preact-render-to-string",
```

Previously, if one attempted `require('react-dom/server')`, the library would accept `react-dom` as the appropriate alias to use. This PR resolves that by sorting the alias names and then traversing that list to look for the longest match.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -21,12 +22,15 @@ Module._nodeModulePaths = function (from) {
 
 var oldResolveFilename = Module._resolveFilename
 Module._resolveFilename = function (request, parent, isMain) {
-  for (var alias in moduleAliases) {
+  for (var i = moduleAliasNames.length; i-- > 0;) {
```
Comment (thomas-p-wilson) [inline index.js]: Reverse sorting is faster than forward sorting, which is just fine since it means we don't need to do an `Array.prototype.reverse()` call on line 93.

File: index.js [hunk 2]
```diff
@@ -21,12 +22,15 @@ Module._nodeModulePaths = function (from) {
...
+    var alias = moduleAliasNames[i]
     if (isPathMatchesAlias(request, alias)) {
       request = nodePath.join(
         moduleAliases[alias],
         request.substr(alias.length)
       )
+      // Only use the first match
+      break
```
Comment (thomas-p-wilson) [inline index.js]: Overwriting our previous matches results in unexpected behaviour for future matches due to the `String.prototype.substr()` call on line 30. Altering this did not break any tests and results in a definitive match on the longest alias.

File: index.js [hunk 3]
```diff
@@ -86,6 +87,9 @@ function addAliases (aliases) {
 
 function addAlias (alias, target) {
   moduleAliases[alias] = target
+  // Cost of sorting is lower here than during resolution
+  moduleAliasNames = Object.keys(moduleAliases)
```
Comment (thomas-p-wilson) [inline index.js]: Ideally I had wanted to avoid keeping a separate list of alias names, but alas it's not sensible. The alternative would be evaluating the keys of the object and sorting them every time a resolution is made, which incurs a far larger performance penalty. Keeping the `Object.prototype.keys()` evaluation and subsequent sort here means that it runs a handful of times, once for each alias added. Performing it during resolution would mean evaluating it once for every single file require'd which would take far more time overall.

**Comment by thomas-p-wilson** [comment]
No worries!  Glad to help!
